<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/2015-12/05143A2-1-16051.jpg ",93,244);
$z[1][4]['ddimg']="/uploads/allimg/2015-12/05143A2-1-16051.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="800";
$z[1][4]['height']="500";
$z[2]=Array("img"," /uploads/allimg/2015-12/05143A2-1-295L.jpg ",246,395);
$z[2][4]['ddimg']="/uploads/allimg/2015-12/05143A2-1-295L.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="800";
$z[2][4]['height']="500";
$z[3]=Array("img"," /uploads/allimg/2015-12/05143A2-1-3Y59.jpg ",397,546);
$z[3][4]['ddimg']="/uploads/allimg/2015-12/05143A2-1-3Y59.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="800";
$z[3][4]['height']="486";
$z[4]=Array("img"," /uploads/allimg/2015-12/05143A2-1-460W.jpg ",548,697);
$z[4][4]['ddimg']="/uploads/allimg/2015-12/05143A2-1-460W.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="800";
$z[4][4]['height']="500";
$z[5]=Array("img"," /uploads/allimg/2015-12/05143A2-1-5P14.jpg ",699,848);
$z[5][4]['ddimg']="/uploads/allimg/2015-12/05143A2-1-5P14.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="800";
$z[5][4]['height']="478";

?>