<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/2015-12/05162637-1-1S64.jpg ",93,244);
$z[1][4]['ddimg']="/uploads/allimg/2015-12/05162637-1-1S64.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="964";
$z[1][4]['height']="539";
$z[2]=Array("img"," /uploads/allimg/2015-12/05162637-1-2c47.jpg ",246,397);
$z[2][4]['ddimg']="/uploads/allimg/2015-12/05162637-1-2c47.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="965";
$z[2][4]['height']="553";
$z[3]=Array("img"," /uploads/allimg/2015-12/05162637-1-36347.jpg ",399,552);
$z[3][4]['ddimg']="/uploads/allimg/2015-12/05162637-1-36347.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="962";
$z[3][4]['height']="538";

?>