<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/2015-12/051G357-1-152U.jpg ",93,243);
$z[1][4]['ddimg']="/uploads/allimg/2015-12/051G357-1-152U.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1200";
$z[1][4]['height']="900";
$z[2]=Array("img"," /uploads/allimg/2015-12/051G357-1-2OA.jpg ",245,393);
$z[2][4]['ddimg']="/uploads/allimg/2015-12/051G357-1-2OA.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1200";
$z[2][4]['height']="950";
$z[3]=Array("img"," /uploads/allimg/2015-12/051G357-1-36328.jpg ",395,548);
$z[3][4]['ddimg']="/uploads/allimg/2015-12/051G357-1-36328.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1200";
$z[3][4]['height']="1098";

?>