<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/2015-12/051J925-1-1XU.jpg ",93,241);
$z[1][4]['ddimg']="/uploads/allimg/2015-12/051J925-1-1XU.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1200";
$z[1][4]['height']="750";
$z[2]=Array("img"," /uploads/allimg/2015-12/051J925-1-245R.jpg ",243,393);
$z[2][4]['ddimg']="/uploads/allimg/2015-12/051J925-1-245R.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1200";
$z[2][4]['height']="750";
$z[3]=Array("img"," /uploads/allimg/2015-12/051J925-1-321V.jpg ",395,545);
$z[3][4]['ddimg']="/uploads/allimg/2015-12/051J925-1-321V.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1200";
$z[3][4]['height']="750";

?>