<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/2015-12/06145322-1-11313.jpg ",93,246);
$z[1][4]['ddimg']="/uploads/allimg/2015-12/06145322-1-11313.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="600";
$z[1][4]['height']="434";
$z[2]=Array("img"," /uploads/allimg/2015-12/06145322-1-21K9.jpg ",248,399);
$z[2][4]['ddimg']="/uploads/allimg/2015-12/06145322-1-21K9.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="600";
$z[2][4]['height']="450";
$z[3]=Array("img"," /uploads/allimg/2015-12/06145322-1-31495.jpg ",401,554);
$z[3][4]['ddimg']="/uploads/allimg/2015-12/06145322-1-31495.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="600";
$z[3][4]['height']="450";

?>