<li class="div_li_dong" id="gallery[field:id /]" style="opacity: 1; left: 0px;">
						<div class="div1">
						<a href="[field:diyi /]"><img src="[field:litpic /]" width="237" height="213" alt="[field:title/]"></a>
						</div>
						
						<div class="div2">
						<div class="p1">[field:title/]</div>
						<div class="p2"></div>
						<div style="display:none">
						
						[field:id function='Getimgs(@me,10)' /]
						
			             </div>
						 </div>
					</li>
					<script>
								
								$('#gallery[field:id /]').rebox({ selector: 'a' });
								
				</script>