<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/2015-12/05144432-1-1aC.jpg ",93,242);
$z[1][4]['ddimg']="/uploads/allimg/2015-12/05144432-1-1aC.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="966";
$z[1][4]['height']="606";
$z[2]=Array("img"," /uploads/allimg/2015-12/05144432-1-24540.jpg ",244,397);
$z[2][4]['ddimg']="/uploads/allimg/2015-12/05144432-1-24540.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="970";
$z[2][4]['height']="553";

?>