<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/2015-12/05145028-1-15K2.jpg ",93,246);
$z[1][4]['ddimg']="/uploads/allimg/2015-12/05145028-1-15K2.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="2400";
$z[1][4]['height']="1708";
$z[2]=Array("img"," /uploads/allimg/2015-12/05145028-1-24419.jpg ",248,402);
$z[2][4]['ddimg']="/uploads/allimg/2015-12/05145028-1-24419.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1000";
$z[2][4]['height']="750";
$z[3]=Array("img"," /uploads/allimg/2015-12/05145028-1-31018.jpg ",404,558);
$z[3][4]['ddimg']="/uploads/allimg/2015-12/05145028-1-31018.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1000";
$z[3][4]['height']="750";

?>