<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/2015-12/051H028-1-19412.jpg ",93,245);
$z[1][4]['ddimg']="/uploads/allimg/2015-12/051H028-1-19412.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1200";
$z[1][4]['height']="900";
$z[2]=Array("img"," /uploads/allimg/2015-12/051H028-1-21543.jpg ",247,399);
$z[2][4]['ddimg']="/uploads/allimg/2015-12/051H028-1-21543.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1200";
$z[2][4]['height']="825";
$z[3]=Array("img"," /uploads/allimg/2015-12/051H028-1-35405.jpg ",401,553);
$z[3][4]['ddimg']="/uploads/allimg/2015-12/051H028-1-35405.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1200";
$z[3][4]['height']="825";
$z[4]=Array("img"," /uploads/allimg/2015-12/051H028-1-4b03.jpg ",555,704);
$z[4][4]['ddimg']="/uploads/allimg/2015-12/051H028-1-4b03.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="800";
$z[4][4]['height']="914";

?>