<?php
$z[0]=Array("global","",274,301);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",337,364);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",376,402);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",1055,1090);
$z[3][4]['filename']="head.htm";
$z[4]=Array("include","",1153,1190);
$z[4][4]['filename']="banner.htm";
$z[5]=Array("field","",1448,1478);
$z[5][4]['name']="typename";
$z[6]=Array("productimagelist","\r\n	<a href=\"[field:imgsrc/]\"><img src=\"[field:imgsrc/]\"  /></a>\r\n	",1572,1685);
$z[7]=Array("field","",1691,1734);
$z[7][4]['name']="id";
$z[7][4]['function']="Getimgs(@me,8)";
$z[8]=Array("include","",1820,1857);
$z[8][4]['filename']="footer.htm";

?>