{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/2015-12/051GK4-1-16310.jpg' text='' width='1134' height='850'} /uploads/allimg/2015-12/051GK4-1-16310.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/2015-12/051GK4-1-2W41.jpg' text='' width='1134' height='850'} /uploads/allimg/2015-12/051GK4-1-2W41.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/2015-12/051GK4-1-34922.jpg' text='' width='1134' height='850'} /uploads/allimg/2015-12/051GK4-1-34922.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/2015-12/051GK4-1-42J8.jpg' text='' width='1134' height='850'} /uploads/allimg/2015-12/051GK4-1-42J8.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/2015-12/051GK4-1-55J2.jpg' text='' width='1134' height='850'} /uploads/allimg/2015-12/051GK4-1-55J2.jpg {/dede:img}
