<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/2015-12/051GK4-1-16310.jpg ",93,243);
$z[1][4]['ddimg']="/uploads/allimg/2015-12/051GK4-1-16310.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1134";
$z[1][4]['height']="850";
$z[2]=Array("img"," /uploads/allimg/2015-12/051GK4-1-2W41.jpg ",245,393);
$z[2][4]['ddimg']="/uploads/allimg/2015-12/051GK4-1-2W41.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1134";
$z[2][4]['height']="850";
$z[3]=Array("img"," /uploads/allimg/2015-12/051GK4-1-34922.jpg ",395,545);
$z[3][4]['ddimg']="/uploads/allimg/2015-12/051GK4-1-34922.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1134";
$z[3][4]['height']="850";
$z[4]=Array("img"," /uploads/allimg/2015-12/051GK4-1-42J8.jpg ",547,695);
$z[4][4]['ddimg']="/uploads/allimg/2015-12/051GK4-1-42J8.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="1134";
$z[4][4]['height']="850";
$z[5]=Array("img"," /uploads/allimg/2015-12/051GK4-1-55J2.jpg ",697,845);
$z[5][4]['ddimg']="/uploads/allimg/2015-12/051GK4-1-55J2.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="1134";
$z[5][4]['height']="850";

?>