<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/2015-12/05164A8-1-1I91.jpg ",93,243);
$z[1][4]['ddimg']="/uploads/allimg/2015-12/05164A8-1-1I91.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1201";
$z[1][4]['height']="801";
$z[2]=Array("img"," /uploads/allimg/2015-12/05164A8-1-2S62.jpg ",245,395);
$z[2][4]['ddimg']="/uploads/allimg/2015-12/05164A8-1-2S62.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1198";
$z[2][4]['height']="796";

?>