<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/2015-12/05150300-1-15300.jpg ",93,247);
$z[1][4]['ddimg']="/uploads/allimg/2015-12/05150300-1-15300.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1200";
$z[1][4]['height']="800";
$z[2]=Array("img"," /uploads/allimg/2015-12/05150300-1-23N0.jpg ",249,401);
$z[2][4]['ddimg']="/uploads/allimg/2015-12/05150300-1-23N0.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1200";
$z[2][4]['height']="800";

?>