<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/2015-12/05112128-1-15449.jpg ",93,247);
$z[1][4]['ddimg']="/uploads/allimg/2015-12/05112128-1-15449.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1332";
$z[1][4]['height']="750";
$z[2]=Array("img"," /uploads/allimg/2015-12/05112128-1-3TM.jpg ",249,399);
$z[2][4]['ddimg']="/uploads/allimg/2015-12/05112128-1-3TM.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1027";
$z[2][4]['height']="950";
$z[3]=Array("img"," /uploads/allimg/2015-12/05112128-1-4cV.jpg ",401,551);
$z[3][4]['ddimg']="/uploads/allimg/2015-12/05112128-1-4cV.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1173";
$z[3][4]['height']="880";
$z[4]=Array("img"," /uploads/allimg/2015-12/05112128-1-592I.jpg ",553,705);
$z[4][4]['ddimg']="/uploads/allimg/2015-12/05112128-1-592I.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="1391";
$z[4][4]['height']="740";

?>