<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/2015-12/05164204-1-1a58.jpg ",93,245);
$z[1][4]['ddimg']="/uploads/allimg/2015-12/05164204-1-1a58.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1200";
$z[1][4]['height']="959";
$z[2]=Array("img"," /uploads/allimg/2015-12/05164204-1-23959.jpg ",247,402);
$z[2][4]['ddimg']="/uploads/allimg/2015-12/05164204-1-23959.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1200";
$z[2][4]['height']="1083";

?>