<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/2015-12/05155K9-1-15H1.jpg ",93,243);
$z[1][4]['ddimg']="/uploads/allimg/2015-12/05155K9-1-15H1.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1200";
$z[1][4]['height']="819";
$z[2]=Array("img"," /uploads/allimg/2015-12/05155K9-1-2b07.jpg ",245,395);
$z[2][4]['ddimg']="/uploads/allimg/2015-12/05155K9-1-2b07.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1200";
$z[2][4]['height']="855";
$z[3]=Array("img"," /uploads/allimg/2015-12/05155K9-1-35140.jpg ",397,549);
$z[3][4]['ddimg']="/uploads/allimg/2015-12/05155K9-1-35140.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1200";
$z[3][4]['height']="857";
$z[4]=Array("img"," /uploads/allimg/2015-12/05155K9-1-4A41.jpg ",551,701);
$z[4][4]['ddimg']="/uploads/allimg/2015-12/05155K9-1-4A41.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="1200";
$z[4][4]['height']="764";

?>