<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/2015-12/05153359-1-111S.jpg ",93,245);
$z[1][4]['ddimg']="/uploads/allimg/2015-12/05153359-1-111S.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1200";
$z[1][4]['height']="743";
$z[2]=Array("img"," /uploads/allimg/2015-12/05153359-1-21050.jpg ",247,402);
$z[2][4]['ddimg']="/uploads/allimg/2015-12/05153359-1-21050.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1200";
$z[2][4]['height']="1331";

?>