<?php
$z[0]=Array("channelartlist","\r\n      <li> <a href=\"{dede:field name='typeurl'/}\" >{dede:field name='typename'/}</a>\r\n        <div id=\"nav2\"> {dede:channel type='son' noself='yes'} <a href=\"[field:typelink/]\" class=\"zl[field:global runphp='yes' name=autoindex](@me < 1)?@me='no_bg\":@me=\"\";[/field:global]\" >[field:typename/]</a> {/dede:channel} </div>\r\n      </li>\r\n      ",327,747);
$z[0][4]['typeid']="top";
$z[0][4]['currentstyle']="active";

?>