<?php
$z[0]=Array("global","",642,669);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",705,732);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",744,770);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",1505,1540);
$z[3][4]['filename']="head.htm";
$z[4]=Array("include","",1612,1649);
$z[4][4]['filename']="banner.htm";
$z[5]=Array("arclist","\r\n          <li class=\"div_li_dong\" style=\"opacity: 1; left: 0px;\">\r\n            <div class=\"div1\"> <a href=\"/news/\"><img src=\"[field:litpic /]\"  alt=\"[field:title /]\"></a> </div>\r\n            <div class=\"div2\">\r\n              <div class=\"p1\">[field:title /]</div>\r\n            </div>\r\n          </li>\r\n          ",2267,2629);
$z[5][4]['row']="5";
$z[5][4]['typeid']="1";
$z[6]=Array("arclist","\r\n          <li class=\"div_li_dong\" style=\"opacity: 1; left: 0px;\">\r\n            <div class=\"div1\"> <a href=\"/classic/\"><img src=\"[field:litpic /]\"  alt=\"[field:title /]\"></a> </div>\r\n            <div class=\"div2\">\r\n              <div class=\"p1\">[field:title /]</div>\r\n            </div>\r\n          </li>\r\n          ",3375,3740);
$z[6][4]['row']="5";
$z[6][4]['typeid']="2";
$z[7]=Array("arclist","\r\n          <li class=\"div_li_dong\" style=\"opacity: 1; left: 0px;\">\r\n            <div class=\"div1\"> <a href=\"/indool/\"><img src=\"[field:litpic /]\"  alt=\"[field:title /]\"></a> </div>\r\n            <div class=\"div2\">\r\n              <div class=\"p1\">[field:title /]</div>\r\n            </div>\r\n          </li>\r\n          ",4487,4851);
$z[7][4]['row']="5";
$z[7][4]['typeid']="3";
$z[8]=Array("arclist","\r\n          <li class=\"div_li_dong\" style=\"opacity: 1; left: 0px;\">\r\n            <div class=\"div1\"> <a href=\"/building/\"><img src=\"[field:litpic /]\"  alt=\"[field:title /]\"></a> </div>\r\n            <div class=\"div2\">\r\n              <div class=\"p1\">[field:title /]</div>\r\n            </div>\r\n          </li>\r\n          ",5601,5967);
$z[8][4]['row']="5";
$z[8][4]['typeid']="4";
$z[9]=Array("arclist","\r\n          <div class=\"post-prev-title\">\r\n            <h3><a class=\"a-text\" href=\"/space/\">[field:title /]</a></h3>\r\n          </div>\r\n          <div class=\"post-prev-info\"> [field:pubdate function=\"GetDateMK(@me)\"/] </div>\r\n          ",19065,19365);
$z[9][4]['typeid']="5";
$z[9][4]['row']="3";
$z[9][4]['titlelen']="40";
$z[10]=Array("include","",20268,20305);
$z[10][4]['filename']="footer.htm";

?>