<?php
$z[0]=Array("global","",274,301);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",337,364);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",376,402);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",1426,1461);
$z[3][4]['filename']="head.htm";
$z[4]=Array("include","",1524,1561);
$z[4][4]['filename']="banner.htm";
$z[5]=Array("field","",1820,1850);
$z[5][4]['name']="typename";
$z[6]=Array("list","\r\n		<div class=\"grid\">\r\n			<a href=\"[field:arcurl/]\" id=\"tanchu\">\r\n			<div class=\"iconq\">&nbsp;</div>\r\n			<div class=\"imgholder\">\r\n				<img src=\"[field:litpic function=firstimg('@me')/]\" />\r\n			</div>\r\n			<strong>[field:title/]</strong>\r\n			<p>[field:description /]</p>\r\n			<div class=\"meta\">by [field:writer /]</div>\r\n			</a>\r\n		</div>\r\n		",1976,2354);
$z[6][4]['pagesize']="12";
$z[7]=Array("pagelist","",2436,2507);
$z[7][4]['listsize']="5";
$z[7][4]['listitem']="info,index,end,pre,next,pageno";
$z[8]=Array("include","",2606,2643);
$z[8][4]['filename']="footer.htm";

?>