<?php
$z[0]=Array("global","",274,301);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",337,364);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",376,402);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",1794,1829);
$z[3][4]['filename']="head.htm";
$z[4]=Array("include","",1892,1929);
$z[4][4]['filename']="banner.htm";
$z[5]=Array("channel","\r\n				<div class=\"div2 rg\" id=\"zh_pro4\" style=\"opacity: 1; right: 0px;\"><a href=\"[field:typelink/]\">| [field:typename/]</a></div>\r\n				",2288,2542);
$z[5][4]['type']="son";
$z[5][4]['typeid']="8";
$z[5][4]['currentstyle']="<a class=";
$z[5][4]['active" href']="~typelink~";
$z[5][4]['>| ~typename~</a>"']="";
$z[6]=Array("arclist","\r\n					<li class=\"div_li_dong\" id=\"gallery[field:id /]\" style=\"opacity: 1; left: 0px;\">\r\n						<div class=\"div1\">\r\n						<a href=\"[field:diyi /]\"><img src=\"[field:litpic /]\" width=\"237\" height=\"213\" alt=\"[field:title/]\"></a>\r\n						</div>\r\n						\r\n						<div class=\"div2\">\r\n						<div class=\"p1\">[field:title/]</div>\r\n						<div class=\"p2\"></div>\r\n						<div style=\"display:none\">\r\n						\r\n						[field:id function='Getimgs(@me,10)' /]\r\n						\r\n			             </div>\r\n						 </div>\r\n					</li>\r\n					<script>\r\n								\r\n								\$('#gallery[field:id /]').rebox({ selector: 'a' });\r\n								\r\n				</script>\r\n					",2798,3489);
$z[6][4]['row']="9";
$z[6][4]['typeid']="8";
$z[6][4]['channelid']="2";
$z[6][4]['addfields']="diyi";
$z[7]=Array("channel","\r\n				<div class=\"div2 rg\" id=\"zh_pro4\" style=\"opacity: 1; right: 0px;\"><a href=\"[field:typelink/]\">| [field:typename/]</a></div>\r\n				",4235,4489);
$z[7][4]['type']="son";
$z[7][4]['typeid']="9";
$z[7][4]['currentstyle']="<a class=";
$z[7][4]['active" href']="~typelink~";
$z[7][4]['>| ~typename~</a>"']="";
$z[8]=Array("arclist","\r\n					<li class=\"div_li_dong\" id=\"gallery[field:id /]\" style=\"opacity: 1; left: 0px;\">\r\n						<div class=\"div1\">\r\n						<a href=\"[field:diyi /]\"><img src=\"[field:litpic /]\" width=\"237\" height=\"213\" alt=\"[field:title/]\"></a>\r\n						</div>\r\n						\r\n						<div class=\"div2\">\r\n						<div class=\"p1\">[field:title/]</div>\r\n						<div class=\"p2\"></div>\r\n						<div style=\"display:none\">\r\n						\r\n						[field:id function='Getimgs(@me,10)' /]\r\n						\r\n			             </div>\r\n						 </div>\r\n					</li>\r\n					<script>\r\n								\r\n								\$('#gallery[field:id /]').rebox({ selector: 'a' });\r\n								\r\n				</script>\r\n					",4739,5430);
$z[8][4]['row']="9";
$z[8][4]['typeid']="9";
$z[8][4]['channelid']="2";
$z[8][4]['addfields']="diyi";
$z[9]=Array("include","",5921,5958);
$z[9][4]['filename']="footer.htm";

?>