<?php
$z[0]=Array("global","",310,337);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",349,375);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1182,1217);
$z[2][4]['filename']="head.htm";
$z[3]=Array("include","",1280,1317);
$z[3][4]['filename']="banner.htm";
$z[4]=Array("type","\r\n				<a href=\"[field:typelink /]\">多伦[field:typename /]系列</a>\r\n				",1620,1718);
$z[5]=Array("channel","\r\n				<a href=\"[field:typelink/]\">| [field:typename/] </a>\r\n				",1763,1935);
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<a class='active' href='~typelink~'>| ~typename~</a>";
$z[6]=Array("list","\r\n					<li class=\"div_li_dong\" id=\"gallery[field:id /]\" style=\"opacity: 1; left: 0px;\">\r\n						<div class=\"div1\">\r\n						<a href=\"[field:diyi /]\"><img src=\"[field:litpic /]\" width=\"237\" height=\"213\" alt=\"[field:title/]\"></a>\r\n						</div>\r\n						\r\n						<div class=\"div2\">\r\n						<div class=\"p1\">[field:title/]</div>\r\n						<div class=\"p2\"></div>\r\n						<div style=\"display:none\">\r\n						\r\n						[field:id function='Getimgs(@me,10)' /]\r\n						\r\n			             </div>\r\n						 </div>\r\n					</li>\r\n					",2033,2566);
$z[6][4]['row']="19";
$z[7]=Array("type","\r\n					<a href=\"[field:typelink /]\"><img src=\"/uploads/image/20150417/1429204607.jpg\"  alt=\"更多\"></a>\r\n					",2671,2805);
$z[8]=Array("list","\r\n								\$('#gallery[field:id /]').rebox({ selector: 'a' });\r\n								",2924,3027);
$z[8][4]['row']="19";
$z[9]=Array("pagelist","",3203,3274);
$z[9][4]['listsize']="5";
$z[9][4]['listitem']="info,index,end,pre,next,pageno";
$z[10]=Array("include","",3391,3428);
$z[10][4]['filename']="footer.htm";

?>