<?php
$z[0]=Array("global","",274,301);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",337,364);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",376,402);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",1802,1837);
$z[3][4]['filename']="head.htm";
$z[4]=Array("include","",1900,1937);
$z[4][4]['filename']="banner.htm";
$z[5]=Array("field","",2240,2270);
$z[5][4]['name']="typename";
$z[6]=Array("list","\r\n					<li class=\"div_li_dong\" id=\"gallery[field:id /]\" style=\"opacity: 1; left: 0px;\">\r\n						<div class=\"div1\">\r\n						<a href=\"[field:diyi /]\"><img src=\"[field:litpic /]\" width=\"237\" height=\"213\" alt=\"[field:title/]\"></a>\r\n						</div>\r\n						\r\n						<div class=\"div2\">\r\n						<div class=\"p1\">[field:title/]</div>\r\n						<div class=\"p2\"></div>\r\n						<div style=\"display:none\">\r\n						\r\n						[field:id function='Getimgs(@me,10)' /]\r\n						\r\n			             </div>\r\n						 </div>\r\n					</li>\r\n					",2362,2895);
$z[6][4]['row']="20";
$z[7]=Array("list","\r\n								\$('#gallery[field:id /]').rebox({ selector: 'a' });\r\n								",2927,3030);
$z[7][4]['row']="20";
$z[8]=Array("pagelist","",3200,3271);
$z[8][4]['listsize']="5";
$z[8][4]['listitem']="info,index,end,pre,next,pageno";
$z[9]=Array("include","",3388,3425);
$z[9][4]['filename']="footer.htm";

?>